### ISSUE TITLE
Missed highlights for methods in 1.1.3

### ISSUE THREAD

**Issue by vnemiro** [telamonian/theme-darcula#10]
Hi! Thank you for great theme for jupyterlab.

Highlights for method disappeared after last extension update to 1.1.3
![image](https://user-images.githubusercontent.com/30344905/66492052-73428000-eabc-11e9-8f09-65d6fea5eab5.png)

I have jupyterlab 1.1.4
python 3.7.4

Thanks!

**Comment by telamonian** [comment]
That's an intentional change that I made in a52d74d481cfef5ff942afeb9debd046abcdbeef as part of fixing #9. No highlights on methods more closely matches the original Darcula theme in Intellij:

![image](https://user-images.githubusercontent.com/2263641/66513891-12aa4780-eaaa-11e9-964f-baa714352916.png)

The original Darcula theme serves as the design reference for this Jlab theme, which aims to match the original as closely as possible. So this issue is a "won't fix".

What I will consider doing is adding settings for user overrides of theme colors to Jlab core. That way, if you're not happy with any of the color decisions I've made in this theme, you'll be able to override them yourself. I'll leave this issue open as a reminder.
